// Generated by Kirito04800's product
//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//

import Foundation

class ___FILEBASENAMEASIDENTIFIER___ {
    
    //MARK: - Properties
    
}
