// Generated by Kirito04800's product
//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//

import Foundation
import UIKit

class ___FILEBASENAMEASIDENTIFIER___: UIViewController {
    
    //MARK: - Properties
    
    //MARK: - ViewController
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // let myVC = Bundle.main.loadNibNamed("MyViewController", owner: self, options: nil)?[0] as? MyViewController
        
    }
    
    //MARK: - Init
    
    init() {
        //super.init(nibName: "MyViewController", bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    //MARK: - Methods
    
}
